### ISSUE TITLE
Provide option to have `isuri` expect only valid URI characters.

### ISSUE THREAD

**Issue by stevecj** [tkem/uritools#70]
The `isuri` function returns `True` for strings that include characters that are not valid in a URI or that contain invalid `%` escapes.

I presume that is by design and should not be changed as the default behavior, but could we have an option something like `only_valid_chars=False`  to which we can pass `True` to cause character correctness to also be checked? An alternative approach could be to have a separate function to perform that check.

I am asking this because I wrote code to do this myself that turned out to be incorrect, so it would be nice to have a correct implementation provided to begin with. My incorrect approach was to test that all characters are in either `RESERVED` or `UNRESERVED`, but that turned out to reject any strings with `%` escape sequences. What I now believe to be a correct regular expression to ensure that characters are valid is as follows:
```python
    VALID_URL_CHARS_REGEX = (
        r'\A(['
        + re.escape(uritools.UNRESERVED + uritools.RESERVED)
        + r']|%[\da-fA-F]{2})*\Z'
    )
```

**Comment by stevecj** [comment]
I'm checking back since I have had no reply. If I were to try to create a pull request for something like this, would it be considered?

I was thinking that `isuri` might have a new optional keyword argument to have it return `False` when invalid characters are present. Maybe something like `check_chars=False` for the argument?

**Comment by tkem** [comment]
@stevecj: Sorry for the delay, "real life" kept me busy.

`uritools` is basically built on the principle "be strict in what you serve, be liberal in what you accept".

So `isuri` et al. are quite forgiving about input, wheres e.g. `uricompose` tries to only create "valid" URIs.

This should maybe be stated more clearly in the docs (PRs regarding docs will _always_ be considered).

Regarding optional keyword arguments, this would have to be added to _all_ the `is...` functions for consistency - at least for now I'd really prefer seperate functions for that, and that don't necessarily _have_ to be part of `uritools`, due to increased maintenance costs (and of course you'd have to provide docs and unit tests for that, too).

So may I suggest you provide your own module for that, depending on/using `uritools` as you see fit?

Kind Regards,
Thomas

P.S.: There's also another library (https://pypi.org/project/rfc3986/) which does provide more strict validation IIRC, so maybe that's more like what you're after.

**Comment by stevecj** [comment]
Thanks very much for your answer. :)
